---
stages:
  - test
  - update-check
  - update

.go_template_defaults:
  stage: test
  allow_failure: true
include:
  - remote: https://gitlab.com/bonsai-oss/organization/ci-templates/-/raw/main/templates/language/go.yml

check update:
  image: registry.fsrv.services/fsrvcorp/container/debian-base:latest@sha256:a1a40b6da1e84449d9fcd37d7cc2f4e23ba0db1c3d33f11b083a09e7211b4b07
  stage: update-check
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - apt update
    - apt install -y curl python3 bash jq
  script:
    - export DEB_VERSION=$(curl https://sources.debian.org/api/src/distro-info-data/ | jq -r '.versions[0].version')
    - bash -x data/generator.sh ubuntu,debian $DEB_VERSION
    - echo "DEB_VERSION=$DEB_VERSION" > data.env
  artifacts:
    reports:
      dotenv:
        - data.env
    when: always
    paths:
      - data/*.json

commit_update:
  image: registry.fsrv.services/fsrvcorp/container/debian-base:latest@sha256:a1a40b6da1e84449d9fcd37d7cc2f4e23ba0db1c3d33f11b083a09e7211b4b07
  stage: update
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  needs:
    - check update
  before_script:
    - apt update
    - apt install -y openssh-client jq python3
    - eval $(ssh-agent)
    - cat ${UPDATE_SSH_KEY} | ssh-add -
    - git config user.email "bot@fsrv.xyz"
    - git config user.name "gitlab-bot"
    - git remote remove update_origin || true
    - git remote add update_origin "git@$CI_SERVER_HOST:$CI_PROJECT_PATH.git"
    - mkdir ~/.ssh && ssh-keyscan -H $CI_SERVER_HOST >> ~/.ssh/known_hosts
  script:
    - |
      if test -n "$(git status --porcelain)"; then
        git checkout -b "update_deb_${DEB_VERSION}"
        git add data/*.json
        git commit -m "update dist-info-data debian package ${DEB_VERSION}"
        git push update_origin HEAD -o merge_request.create \
          -o merge_request.target=${CI_DEFAULT_BRANCH} \
          -o merge_request.assign=${GITLAB_USER_LOGIN} \
          -o merge_request.title="update dist-info-data debian package ${DEB_VERSION}" \
          -o merge_request.label="Source::CI"
      fi
