---
stages:
  - test
  - update-check
  - update

lint:
  image: registry.gitlab.com/gitlab-org/gitlab-build-images:golangci-lint-alpine
  stage: test
  script:
    - golangci-lint run ./... --issues-exit-code 0 --out-format code-climate | tee gl-code-quality-report.json | jq -r '.[] | "\(.location.path):\(.location.lines.begin) \(.description)"'
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths:
      - gl-code-quality-report.json

go_fmt:
  image: golang
  stage: test
  script:
    - go fmt ./...

go_test:
  image: golang
  stage: test
  before_script:
    - go install gotest.tools/gotestsum@latest
  script:
    - go fmt ./...
    - go test -v ./...
    - /go/bin/gotestsum --junitfile report.xml --format testname
  artifacts:
    when: always
    reports:
      junit: report.xml

check update:
  image: registry.fsrv.services/fsrvcorp/container/debian-base:latest
  stage: update-check
  needs:
    - go_fmt
    - go_test
    - lint
  before_script:
    - apt update
    - apt install -y curl python3 bash jq
  script:
    - export DEB_VERSION=$(curl https://sources.debian.org/api/src/distro-info-data/ | jq -r '.versions[0].version')
    - bash -x data/generator.sh ubuntu,debian $DEB_VERSION
  artifacts:
    when: always
    paths:
      - data/*.json

commit_update:
  image: registry.fsrv.services/fsrvcorp/container/debian-base:latest
  stage: update
  needs:
    - check update
  before_script:
    - apt update
    - apt install -y openssh-client jq python3
    - eval $(ssh-agent)
    - cat ${UPDATE_SSH_KEY} | ssh-add -
    - git config user.email "bot@fsrv.xyz"
    - git config user.name "gitlab-bot"
    - git remote remove update_origin || true
    - git remote add update_origin "git@$CI_SERVER_HOST:$CI_PROJECT_PATH.git"
    - mkdir ~/.ssh && ssh-keyscan -H $CI_SERVER_HOST >> ~/.ssh/known_hosts
  script:
    - |
      if test -n "$(git status --porcelain)"; then
        git checkout -b "update_deb_$(date +%F_%H-%M)"
        git add data/*.json
        git commit -m "update dist-info-data debian package $(date +%F_%H:%M)"
        git push update_origin HEAD
      fi

